"""Transcripts of YouTube videos as Markdown files (with timestamps) or SRT subtitles.

Usage:
    export APIFY_TOKEN=your_token      # Windows PowerShell: $env:APIFY_TOKEN="your_token"
    python transcripts.py https://youtu.be/arj7oStGLkU https://www.youtube.com/watch?v=dQw4w9WgXcQ --lang en
    python transcripts.py videos.txt --format srt          # a text file with one link per line
"""
import argparse
import os
import re
from pathlib import Path

from apify_client import ApifyClient

ACTOR = "fguiraud/youtube-transcript-scraper"

parser = argparse.ArgumentParser()
parser.add_argument("videos", nargs="+", help="Video links or IDs, or a .txt file with one per line")
parser.add_argument("--lang", default="en", help="Preferred caption languages, comma-separated (e.g. es,en)")
parser.add_argument("--format", default="markdown", choices=["markdown", "srt", "text"])
parser.add_argument("--out", default="transcripts")
args = parser.parse_args()

videos = []
for v in args.videos:
    videos += Path(v).read_text(encoding="utf-8").split() if v.endswith(".txt") else [v]

client = ApifyClient(os.environ["APIFY_TOKEN"])
run = client.actor(ACTOR).call(run_input={
    "videos": videos,
    "languages": [x.strip() for x in args.lang.split(",") if x.strip()],
    "outputs": [args.format],
})

out = Path(args.out)
out.mkdir(exist_ok=True)
ext = {"markdown": "md", "srt": "srt", "text": "txt"}[args.format]
for item in client.dataset(run.default_dataset_id).iterate_items():
    if item.get("status") != "ok":
        print(f"[{item.get('status')}] {item.get('url') or item.get('input')}: {item.get('note') or item.get('error')}")
        continue
    name = re.sub(r"[^\w\- ]+", "", item["title"])[:80].strip() or item["videoId"]
    (out / f"{name}.{ext}").write_text(item[args.format], encoding="utf-8")
    kind = "auto-generated" if item["isAutoGenerated"] else "human"
    print(f"[saved] {item['title']} ({item['language']}, {kind} captions, {item['wordCount']} words)")

print(f"\nFiles in ./{out}/")
